import type { BootkitOrder, OrderStatus, PaymentStatus } from "@/types/order";
import type { Product } from "@/types/product";

type ApiResponse<T> = { success: boolean; message?: string; data?: T };
type BackendOrder = { _id?: string; id?: string; orderNumber: string; items: Array<{ product: string; name: string; thumbnail: string; quantity: number; mrp: number; sellingPrice: number; total: number }>; address?: { fullName?: string; phone?: string; addressLine1?: string; addressLine2?: string; landmark?: string; city?: string; state?: string; postalCode?: string }; paymentMethod: string; paymentStatus: string; status: string; subtotal: number; deliveryCharge: number; grandTotal: number; discount: number; couponCode?: string; couponDiscount?: number; createdAt: string; updatedAt: string };
type Pagination = { page: number; limit: number; total: number; totalPages: number };
const statusMap: Record<string, OrderStatus> = { PLACED: "Placed", CONFIRMED: "Confirmed", PACKING: "Packing", OUT_FOR_DELIVERY: "Out for Delivery", DELIVERED: "Delivered", CANCELLED: "Cancelled", PENDING: "Placed" };
const paymentMap: Record<string, PaymentStatus> = { PENDING: "Pending", PAID: "Paid", FAILED: "Failed" };
function url(path: string) { return `${(process.env.NEXT_PUBLIC_API_BASE_URL || "/api").replace(/\/$/, "")}${path}`; }
function toOrder(order: BackendOrder): BootkitOrder {
  const id = order.id || order._id; if (!id) throw new Error("Order response is missing an identifier.");
  const address = order.address ?? {};
  return { id, orderNumber: order.orderNumber, items: order.items.map((item) => ({ quantity: item.quantity, product: { id: item.product, name: item.name, image: item.thumbnail, thumbnail: item.thumbnail, gallery: [], description: "", slug: "", brand: "", categorySlug: "", sku: "", barcode: "", fallbackIcon: "", unit: { label: "", value: "" }, mrp: item.mrp, price: item.sellingPrice, stock: 0, deliveryMinutes: 0, featured: false, bestseller: false, showOnHome: false, displayOrder: 0, active: true } as unknown as Product })), address: { fullName: address.fullName ?? "", phone: address.phone ?? "", houseNumber: address.addressLine1 ?? "", street: address.addressLine2 ?? "", area: "", landmark: address.landmark ?? "", city: address.city ?? "", state: address.state ?? "", pincode: address.postalCode ?? "", addressType: "Home" }, paymentMethod: order.paymentMethod as BootkitOrder["paymentMethod"], paymentStatus: paymentMap[order.paymentStatus] ?? "Pending", status: statusMap[order.status] ?? "Placed", itemTotal: order.subtotal, deliveryFee: order.deliveryCharge, totalAmount: order.grandTotal, savings: order.discount, offerCode: order.couponCode || undefined, offerDiscount: order.couponDiscount || undefined, createdAt: order.createdAt, updatedAt: order.updatedAt };
}
async function request<T>(path: string, token: string, init: RequestInit = {}) { const response = await fetch(url(path), { ...init, headers: { Authorization: `Bearer ${token}`, ...init.headers } }); const payload = await response.json() as ApiResponse<T>; if (!response.ok || !payload.success || payload.data === undefined) throw new Error(payload.message || "Order request failed."); return payload.data; }
export async function getAdminOrders(token: string, params: { page?: number; search?: string; status?: string } = {}) { const query = new URLSearchParams({ page: String(params.page ?? 1), limit: "20" }); if (params.search?.trim()) query.set("search", params.search.trim()); if (params.status) query.set("status", params.status); const data = await request<{ items: BackendOrder[]; pagination: Pagination }>(`/admin/orders?${query}`, token); return { orders: data.items.map(toOrder), pagination: data.pagination }; }
export async function updateAdminOrderStatus(token: string, orderNumber: string, status: OrderStatus) { const backendStatus = status.replaceAll(" ", "_").toUpperCase(); return toOrder(await request<BackendOrder>(`/admin/orders/${orderNumber}/status`, token, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: backendStatus }) })); }
