"use client";

import {
  CheckCircle2,
  Clock3,
  Eye,
  MapPin,
  Pencil,
  Phone,
  Plus,
  Power,
  Store,
  Trash2,
  UserRound,
  X,
} from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import Container from "@/components/ui/Container";
import Header from "@/components/layout/Header";
import {
  ImageUploader,
  type ImageUploaderItem,
} from "@/components/admin/media";
import AdminEmptyState from "@/components/admin/ui/AdminEmptyState";
import AdminLoadingSkeleton from "@/components/admin/ui/AdminLoadingSkeleton";
import AdminPageHeader from "@/components/admin/ui/AdminPageHeader";
import AdminPagination from "@/components/admin/ui/AdminPagination";
import AdminPrimaryButton from "@/components/admin/ui/AdminPrimaryButton";
import AdminSearchBar from "@/components/admin/ui/AdminSearchBar";
import AdminStatusBadge from "@/components/admin/ui/AdminStatusBadge";

type StoreStatus = "Active" | "Inactive";
type StoreFilter = "All" | StoreStatus;

type AdminStore = {
  id: string;
  name: string;
  code: string;
  managerName: string;
  contactNumber: string;
  city: string;
  deliveryRadius: number;
  status: StoreStatus;
  address: string;
  state: string;
  pinCode: string;
  deliveryArea: string;
  workingHours: string;
  logo: ImageUploaderItem[];
  banner: ImageUploaderItem[];
};

const initialStores: AdminStore[] = [
  {
    id: "store_001",
    name: "BootKit Main Store",
    code: "BKT-SDR-01",
    managerName: "Rakesh Sharma",
    contactNumber: "9876543210",
    city: "Sardarshahar",
    deliveryRadius: 8,
    status: "Active",
    address: "Main Market, Ward 12",
    state: "Rajasthan",
    pinCode: "331403",
    deliveryArea: "Sardarshahar city and nearby wards",
    workingHours: "8:00 AM - 10:00 PM",
    logo: [],
    banner: [],
  },
  {
    id: "store_002",
    name: "BootKit Churu Road",
    code: "BKT-SDR-02",
    managerName: "Poonam Verma",
    contactNumber: "9876543211",
    city: "Sardarshahar",
    deliveryRadius: 5,
    status: "Active",
    address: "Churu Road, Near Bus Stand",
    state: "Rajasthan",
    pinCode: "331403",
    deliveryArea: "Churu Road, Bus Stand and Station Road",
    workingHours: "9:00 AM - 9:00 PM",
    logo: [],
    banner: [],
  },
  {
    id: "store_003",
    name: "BootKit Bidasar Road",
    code: "BKT-SDR-03",
    managerName: "Deepak Saini",
    contactNumber: "9876543212",
    city: "Sardarshahar",
    deliveryRadius: 6,
    status: "Inactive",
    address: "Bidasar Road, New Colony",
    state: "Rajasthan",
    pinCode: "331403",
    deliveryArea: "Bidasar Road and New Colony",
    workingHours: "9:00 AM - 8:00 PM",
    logo: [],
    banner: [],
  },
];

const filters: StoreFilter[] = ["All", "Active", "Inactive"];
const pageSize = 4;

function StoreImage({
  items,
  label,
  className,
}: {
  items: ImageUploaderItem[];
  label: string;
  className: string;
}) {
  const image = items[0];

  if (image) {
    return (
      // Preview URLs are locally generated by ImageUploader until backend storage is connected.
      // eslint-disable-next-line @next/next/no-img-element
      <img src={image.url} alt={label} className={className} />
    );
  }

  return (
    <div
      className={`${className} flex items-center justify-center bg-[var(--surface-soft)] text-[var(--text-muted)]`}
      aria-label={`${label} placeholder`}
    >
      <Store size={22} />
    </div>
  );
}

export default function AdminStoresClient() {
  const [stores, setStores] = useState<AdminStore[]>(initialStores);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<StoreFilter>("All");
  const [page, setPage] = useState(1);
  const [selectedStore, setSelectedStore] = useState<AdminStore | null>(null);
  const [message, setMessage] = useState("");
  const [isLoading] = useState(false);

  const filteredStores = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();

    return stores.filter((store) => {
      const matchesQuery =
        !normalizedQuery ||
        [store.name, store.city].some((value) =>
          value.toLowerCase().includes(normalizedQuery)
        );
      const matchesFilter =
        filter === "All" || store.status === filter;

      return matchesQuery && matchesFilter;
    });
  }, [filter, query, stores]);

  const totalPages = Math.max(
    1,
    Math.ceil(filteredStores.length / pageSize)
  );
  const visibleStores = filteredStores.slice(
    (page - 1) * pageSize,
    page * pageSize
  );

  const changeFilter = (nextFilter: StoreFilter) => {
    setFilter(nextFilter);
    setPage(1);
  };

  const toggleStoreStatus = (store: AdminStore) => {
    const nextStatus: StoreStatus =
      store.status === "Active" ? "Inactive" : "Active";

    setStores((current) =>
      current.map((item) =>
        item.id === store.id ? { ...item, status: nextStatus } : item
      )
    );
    setSelectedStore((current) =>
      current?.id === store.id
        ? { ...current, status: nextStatus }
        : current
    );
    setMessage(`${store.name} is ${nextStatus.toLowerCase()} in this preview session.`);
  };

  const deleteStore = (store: AdminStore) => {
    setStores((current) => current.filter((item) => item.id !== store.id));
    setSelectedStore((current) =>
      current?.id === store.id ? null : current
    );
    setMessage(`${store.name} was removed in this preview session.`);
  };

  const updateStoreImages = (
    store: AdminStore,
    field: "logo" | "banner",
    items: ImageUploaderItem[]
  ) => {
    setStores((current) =>
      current.map((item) =>
        item.id === store.id ? { ...item, [field]: items } : item
      )
    );
    setSelectedStore((current) =>
      current?.id === store.id ? { ...current, [field]: items } : current
    );
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[var(--background)]">
        <Header />
        <Container className="py-6">
          <AdminLoadingSkeleton variant="page" className="h-[720px]" />
        </Container>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[var(--background)]">
      <Header />

      <main>
        <Container className="py-4 sm:py-8">
          <AdminPageHeader
            title="Store management"
            description="Review store availability and delivery coverage"
            action={
              <AdminPrimaryButton
                icon={<Plus size={15} />}
                onClick={() =>
                  setMessage("Store creation will be connected to the approved backend.")
                }
              >
                Add store
              </AdminPrimaryButton>
            }
          />

          {message && (
            <div className="mb-5 flex items-center gap-2 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-xs font-bold text-[var(--success)]">
              <CheckCircle2 size={16} />
              {message}
            </div>
          )}

          <section className="rounded-[24px] border border-[var(--border)] bg-white p-4 shadow-[var(--shadow-sm)]">
            <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
              <AdminSearchBar
                value={query}
                onChange={(event) => {
                  setQuery(event.target.value);
                  setPage(1);
                }}
                placeholder="Search store name or city"
              />

              <div className="flex flex-wrap gap-2">
                {filters.map((item) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() => changeFilter(item)}
                    className={`h-9 rounded-lg px-3 text-[10px] font-black transition ${
                      filter === item
                        ? "bg-[var(--primary)] text-white"
                        : "bg-[var(--surface-soft)] text-[var(--text-muted)]"
                    }`}
                  >
                    {item}
                  </button>
                ))}
              </div>
            </div>
          </section>

          <section className="mt-5">
            {visibleStores.length ? (
              <div className="grid gap-4 lg:grid-cols-2">
                {visibleStores.map((store) => (
                  <article
                    key={store.id}
                    className="overflow-hidden rounded-[24px] border border-[var(--border)] bg-white shadow-[var(--shadow-sm)]"
                  >
                    <div className="relative h-28 overflow-hidden bg-[var(--surface-soft)]">
                      <StoreImage
                        items={store.banner}
                        label={`${store.name} banner`}
                        className="h-full w-full object-cover"
                      />
                      <AdminStatusBadge
                        label={store.status}
                        tone={store.status === "Active" ? "success" : "neutral"}
                        className="absolute right-3 top-3"
                      />
                    </div>

                    <div className="p-4">
                      <div className="flex items-start gap-3">
                        <StoreImage
                          items={store.logo}
                          label={`${store.name} logo`}
                          className="-mt-9 h-16 w-16 shrink-0 rounded-2xl border-4 border-white object-cover shadow-[var(--shadow-sm)]"
                        />
                        <div className="min-w-0 flex-1 pt-1">
                          <p className="truncate text-sm font-black text-[var(--text-primary)]">
                            {store.name}
                          </p>
                          <p className="mt-0.5 text-[10px] font-bold uppercase tracking-[0.08em] text-[var(--text-muted)]">
                            {store.code}
                          </p>
                        </div>
                      </div>

                      <div className="mt-4 grid grid-cols-2 gap-3 text-xs">
                        <StoreDetail icon={<UserRound size={14} />} label="Manager" value={store.managerName} />
                        <StoreDetail icon={<Phone size={14} />} label="Contact" value={store.contactNumber} />
                        <StoreDetail icon={<MapPin size={14} />} label="City" value={store.city} />
                        <StoreDetail icon={<Store size={14} />} label="Delivery radius" value={`${store.deliveryRadius} km`} />
                      </div>

                      <div className="mt-4 flex flex-wrap gap-2 border-t border-[var(--border)] pt-4">
                        <ActionButton
                          label="View"
                          icon={<Eye size={14} />}
                          onClick={() => setSelectedStore(store)}
                        />
                        <ActionButton
                          label="Edit"
                          icon={<Pencil size={14} />}
                          onClick={() =>
                            setMessage("Store editing will be connected to the approved backend.")
                          }
                        />
                        <ActionButton
                          label={store.status === "Active" ? "Disable" : "Enable"}
                          icon={<Power size={14} />}
                          onClick={() => toggleStoreStatus(store)}
                        />
                        <ActionButton
                          label="Delete"
                          icon={<Trash2 size={14} />}
                          destructive
                          onClick={() => deleteStore(store)}
                        />
                      </div>
                    </div>
                  </article>
                ))}
              </div>
            ) : (
              <AdminEmptyState
                title={Boolean(query) || filter !== "All" ? "No stores found" : "No stores yet"}
                description={
                  Boolean(query) || filter !== "All"
                    ? "Try changing the search or filter to see other stores."
                    : "Stores added through the approved backend will appear here."
                }
                icon={Store}
                className="min-h-0 rounded-[24px] border-dashed py-16"
              />
            )}
          </section>

          {filteredStores.length > pageSize && (
            <AdminPagination
              page={page}
              totalPages={totalPages}
              onPrevious={() => setPage((current) => Math.max(1, current - 1))}
              onNext={() => setPage((current) => Math.min(totalPages, current + 1))}
            />
          )}
        </Container>
      </main>

      {selectedStore && (
        <StoreDrawer
          store={selectedStore}
          onClose={() => setSelectedStore(null)}
          onToggleStatus={() => toggleStoreStatus(selectedStore)}
          onDelete={() => deleteStore(selectedStore)}
          onUpdateImages={updateStoreImages}
        />
      )}
    </div>
  );
}

function StoreDetail({
  icon,
  label,
  value,
}: {
  icon: ReactNode;
  label: string;
  value: string;
}) {
  return (
    <div className="min-w-0 rounded-xl bg-[var(--surface-soft)] px-3 py-2.5">
      <div className="mb-1 flex items-center gap-1.5 text-[var(--text-muted)]">
        {icon}
        <span className="text-[9px] font-black uppercase tracking-[0.08em]">{label}</span>
      </div>
      <p className="truncate text-xs font-bold text-[var(--text-secondary)]">{value}</p>
    </div>
  );
}

function ActionButton({
  label,
  icon,
  destructive = false,
  onClick,
}: {
  label: string;
  icon: ReactNode;
  destructive?: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex h-8 items-center gap-1.5 rounded-lg px-2.5 text-[10px] font-black transition ${
        destructive
          ? "bg-red-50 text-[var(--danger)]"
          : "bg-[var(--surface-soft)] text-[var(--text-secondary)]"
      }`}
    >
      {icon}
      {label}
    </button>
  );
}

function StoreDrawer({
  store,
  onClose,
  onToggleStatus,
  onDelete,
  onUpdateImages,
}: {
  store: AdminStore;
  onClose: () => void;
  onToggleStatus: () => void;
  onDelete: () => void;
  onUpdateImages: (
    store: AdminStore,
    field: "logo" | "banner",
    items: ImageUploaderItem[]
  ) => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/35" role="presentation">
      <aside
        aria-label="Store details"
        className="h-full w-full max-w-md overflow-y-auto bg-white p-5 shadow-[-16px_0_40px_rgba(0,0,0,0.15)] sm:p-6"
      >
        <div className="flex items-start justify-between gap-4">
          <div className="flex min-w-0 items-center gap-3">
            <StoreImage
              items={store.logo}
              label={`${store.name} logo`}
              className="flex h-12 w-12 shrink-0 rounded-xl object-cover"
            />
            <div className="min-w-0">
              <h2 className="truncate text-lg font-black text-[var(--text-primary)]">{store.name}</h2>
              <p className="text-[10px] font-black uppercase tracking-[0.1em] text-[var(--primary)]">{store.code}</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[var(--surface-soft)] text-[var(--text-secondary)]"
            aria-label="Close store details"
          >
            <X size={18} />
          </button>
        </div>

        <div className="mt-5 overflow-hidden rounded-2xl bg-[var(--surface-soft)]">
          <StoreImage
            items={store.banner}
            label={`${store.name} banner`}
            className="h-36 w-full object-cover"
          />
        </div>

        <div className="mt-5 space-y-4">
          <DrawerSection title="Store visuals">
            <ImageUploader
              label="Store logo"
              value={store.logo}
              onChange={(items) => onUpdateImages(store, "logo", items)}
              helperText="Local preview only. Upload storage will be connected later."
            />
            <ImageUploader
              label="Store banner"
              value={store.banner}
              onChange={(items) => onUpdateImages(store, "banner", items)}
              helperText="Local preview only. Upload storage will be connected later."
            />
          </DrawerSection>
          <DrawerSection title="Store information">
            <DrawerRow label="Store code" value={store.code} />
            <DrawerRow label="Current status" value={store.status} />
          </DrawerSection>
          <DrawerSection title="Address">
            <DrawerRow label="Address" value={store.address} />
            <DrawerRow label="City" value={store.city} />
            <DrawerRow label="State / PIN" value={`${store.state} · ${store.pinCode}`} />
          </DrawerSection>
          <DrawerSection title="Delivery area">
            <DrawerRow label="Coverage" value={store.deliveryArea} />
            <DrawerRow label="Delivery radius" value={`${store.deliveryRadius} km`} />
          </DrawerSection>
          <DrawerSection title="Contact details">
            <DrawerRow label="Contact number" value={store.contactNumber} />
          </DrawerSection>
          <DrawerSection title="Working hours">
            <div className="flex items-center gap-2 text-xs font-bold text-[var(--text-secondary)]">
              <Clock3 size={15} className="text-[var(--primary)]" />
              {store.workingHours}
            </div>
          </DrawerSection>
          <DrawerSection title="Manager information">
            <DrawerRow label="Manager name" value={store.managerName} />
          </DrawerSection>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-3 border-t border-[var(--border)] pt-5">
          <button
            type="button"
            onClick={onToggleStatus}
            className="flex h-10 items-center justify-center gap-2 rounded-xl bg-[var(--surface-soft)] text-xs font-black text-[var(--text-secondary)]"
          >
            <Power size={15} />
            {store.status === "Active" ? "Disable" : "Enable"}
          </button>
          <button
            type="button"
            onClick={onDelete}
            className="flex h-10 items-center justify-center gap-2 rounded-xl bg-red-50 text-xs font-black text-[var(--danger)]"
          >
            <Trash2 size={15} />
            Delete store
          </button>
        </div>
      </aside>
    </div>
  );
}

function DrawerSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[var(--border)] p-4">
      <h3 className="mb-3 text-[10px] font-black uppercase tracking-[0.1em] text-[var(--primary)]">{title}</h3>
      <div className="space-y-2.5">{children}</div>
    </section>
  );
}

function DrawerRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4 text-xs">
      <span className="shrink-0 text-[var(--text-muted)]">{label}</span>
      <span className="text-right font-bold text-[var(--text-secondary)]">{value}</span>
    </div>
  );
}
